feat(api): add send answer endpoint
Farma-Authoring-Tool/farma-api pull request #81
Opened 2024-05-16 02:48 UTC by dviniciusbonin

## PR Template

Add send answer endpoint for student

Issue: #80 

### Description
Send answer endpoint for student

### Motivation and Context
Allow sending answer to solution step

### How has this been tested?
This task was tested with the created unit tests and manually

### Screenshots (if appropriate):

### Types of changes

- [ ] fix: A bug fix
- [x] feat: A new feature
- [ ] refactor: A code change that neither fixes a bug nor adds a feature
- [ ] enhancement: An enhancement makes something better
- [ ] test: Adding missing tests or correcting existing tests
- [ ] perf: A code change that improves performance
- [ ] docs: Documentation only changes
- [ ] style: Changes that do not affect the meaning of the code (e.g. prettier format)
- [ ] ci: Changes to our CI configuration files and scripts
- [ ] chore: Changes to the build process or auxiliary tools and libraries functionality to not work as expected

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

---

Hours Required: 5

2024-05-20 21:08 UTC, MarczalTSIGP requested changes

2024-05-20 21:08 UTC, MarczalTSIGP commented on app/controllers/api/view/teams/solution_step_controller.rb
> +      correct: user_answer == @solution_step.response
Essa lógica não deve estar no controler, pode colocar no model.

2024-05-20 21:51 UTC, dviniciusbonin commented on app/controllers/api/view/teams/solution_step_controller.rb
> +      correct: user_answer == @solution_step.response
Ajustado

2024-05-25 12:57 UTC, MarczalTSIGP approved these changes

2024-05-25 12:57 UTC, merged